#!/usr/bin/env bash
# Generated by `esperkit init`. Runs configured quick checks for this project.

FAILED=0

echo "--- esper: lint ---"
bun run lint
if [ $? -ne 0 ]; then
  FAILED=1
fi

echo "--- esper: typecheck ---"
bun run typecheck
if [ $? -ne 0 ]; then
  FAILED=1
fi

echo "--- esper: test ---"
bun run test
if [ $? -ne 0 ]; then
  FAILED=1
fi

if [ "$FAILED" -ne 0 ]; then
  echo "esper: quick verification failed"
  exit 1
fi

echo "esper: quick verification passed"
exit 0
