import './styles/global.css'
import './core/styles/transitions.css'

// Core engine
export { Deck } from './core/Deck'
export type { DeckProps } from './core/Deck'
export { Section } from './core/Section'
export type { SectionProps } from './core/Section'
export { ThemeProvider } from './core/theme/ThemeContext'

export { Slide } from './themes/zurich/Slide'
export type { SlideProps } from './themes/zurich/Slide'

// Default theme pack
export { ProgressBar } from './themes/zurich/ProgressBar'
export { SlideCounter } from './themes/zurich/SlideCounter'
export { Title } from './themes/zurich/Title'
export type { TitleProps } from './themes/zurich/Title'
export { Heading } from './themes/zurich/Heading'
export type { HeadingProps } from './themes/zurich/Heading'
export { Text } from './themes/zurich/Text'
export type { TextProps } from './themes/zurich/Text'
export { BulletPoints } from './themes/zurich/BulletPoints'
export type { BulletPointsProps } from './themes/zurich/BulletPoints'
export { Enumerate } from './themes/zurich/Enumerate'
export type { EnumerateProps } from './themes/zurich/Enumerate'
export { Item } from './themes/zurich/Item'
export type { ItemProps } from './themes/zurich/Item'
export { Code } from './themes/zurich/Code'
export type { CodeProps } from './themes/zurich/Code'
export { Image } from './themes/zurich/Image'
export type { ImageProps } from './themes/zurich/Image'
export { Quote } from './themes/zurich/Quote'
export type { QuoteProps } from './themes/zurich/Quote'
export { Block } from './themes/zurich/Block'
export type { BlockProps } from './themes/zurich/Block'
export { Columns } from './themes/zurich/Columns'
export type { ColumnsProps } from './themes/zurich/Columns'
export { Column } from './themes/zurich/Column'
export type { ColumnProps } from './themes/zurich/Column'

// Views
export { PresenterView } from './views/PresenterView'
export type { PresenterViewProps } from './views/PresenterView'
export { ProjectorView } from './views/ProjectorView'
export type { ProjectorViewProps } from './views/ProjectorView'

// Router
export { DiaposRouter, useRoute } from './router'
export type { DiaposRoute } from './router'

// Hooks
export { useDeck } from './core/hooks/useDeck'
export { usePause } from './core/hooks/usePause'
export { useNotes } from './core/hooks/useNotes'
export { useSyncChannel } from './core/hooks/useSyncChannel'
export { useTheme } from './core/hooks/useTheme'
export { useFullscreen } from './core/hooks/useFullscreen'
export type { DeckState } from './core/context/DeckContext'

export { defaultTheme } from './core/theme/defaultTheme'
export { zurichTheme } from './themes/zurich/theme'
export { genevaTheme } from './themes/geneva/theme'
export { milanTheme } from './themes/milan/theme'
export { viennaTheme } from './themes/vienna/theme'
export { createTheme } from './core/theme/createTheme'
export type { Theme, ThemeColors, ThemeFonts, DeepPartial } from './core/theme/types'
export type { Transition } from './core/types'
